import { getUserRole } from "@/app/actions/profile";
import { getIndividualThread } from "@/app/actions/thread";
import { auth } from "@/auth";
import { SyncedInput } from "@/components/fields/synced-thread-field";
import { SaveThreadButton } from "@/components/tiptap-templates/simple/save-button";
import { SimpleEditor } from "@/components/tiptap-templates/simple/simple-editor";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import { Field, FieldDescription, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";

import type { Metadata } from "next";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Edit | Sweetroll Forums",
  description: "Generated by create next app",
};

export default async function EditThreadPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const { entry: thread } = await getIndividualThread({ id });

  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const { role } = session
    ? await getUserRole({ id: session!.user.id })
    : { role: "USER" };

  if (
    !session ||
    (session && session!.user.id !== thread?.authorId && role !== "ADMIN")
  )
    return (
      <section>
        <h1 className="text-red-700 font-bold text-4xl">UNAUTHORIZED ACCESS</h1>
      </section>
    );

  return (
    <section className="flex flex-col gap-8">
      <form>
        <Card size="sm" className="w-full!">
          <CardHeader>
            <CardTitle>
              <Field>
                <FieldLabel htmlFor="input-field-username">Title</FieldLabel>
                <SyncedInput
                  storeField="title"
                  initialValue={thread!.title || ""}
                  id="input-field-thread-title"
                  type="text"
                  placeholder="Title of this thread..."
                />
              </Field>
            </CardTitle>
            <CardAction className="self-end mb-1">
              <SaveThreadButton threadId={thread!.id} />
            </CardAction>
          </CardHeader>
          <CardContent className="max-w-xl">
            <Field>
              <FieldLabel htmlFor="input-field-username">Tags</FieldLabel>
              <SyncedInput
                storeField="tags"
                initialValue={thread!.tags.join(",") || ""}
                id="input-field-thread-tags"
                type="text"
                placeholder="Tags separated by comma..."
              />
              <FieldDescription>Tags separated by comma.</FieldDescription>
            </Field>
          </CardContent>
        </Card>
      </form>
      <SimpleEditor content={thread!.content} />
    </section>
  );
}
