import getUserProfile from "@/app/actions/profile";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile | Sweetroll Forums",
  description: "Generated by create next app",
};

export default async function ProfilePage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const { profile } = await getUserProfile({ id: slug });

  return (
    <section>
      <div>
        {/* AVATAR */}
        <div></div>
        {/* CONTENT */}
        <div>
          <h1 className="text-xl font-bold">{profile.name}</h1>
        </div>
      </div>
    </section>
  );
}
