import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import TopNavBar from "./components/navigation/top-nav";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  BreadcrumbPage,
} from "@/components/ui/breadcrumb";
import NavigationBreadcrumbs from "@/components/breadcrumbs/navigation";
import { CardNewThreads } from "@/components/navigation/new-threads";

const notoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home | Sweetroll Forums",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        notoSans.variable,
      )}
    >
      <body className="flex min-h-full flex-col items-center gap-8 bg-muted">
        <TopNavBar />
        <aside className="w-full md:max-w-7xl">
          <Card size="sm" className="w-full">
            <CardHeader>
              <CardTitle>
                <NavigationBreadcrumbs />
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold inline-flex gap-2 items-end">
                <span>Sweetroll Forums</span>
                <p className="text-sm font-normal inline-flex gap-1">
                  brought by
                  <span className="text-blue-600 font-semibold">
                    Crescent Sun
                  </span>
                </p>
              </div>
            </CardContent>
          </Card>
        </aside>
        <main className="w-full md:max-w-7xl grid grid-cols-[0.7fr_0.3fr] gap-8">
          {children}
          <div className="flex flex-col gap-8 items-center">
            <CardNewThreads />
          </div>
        </main>
      </body>
    </html>
  );
}
