import { getIndividualThread } from "@/app/actions/thread";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { Metadata } from "next";
import { auth } from "@/auth";
import { headers } from "next/headers";
import { Button } from "@/components/ui/button";
import { Pencil } from "lucide-react";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";
import { getUserRole } from "@/app/actions/profile";

export const metadata: Metadata = {
  title: "Thread | Sweetroll Forums",
  description: "Generated by create next app",
};

export default async function ThreadPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const { entry: thread } = await getIndividualThread({ id });

  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const { role } = session
    ? await getUserRole({ id: session!.user.id })
    : { role: "USER" };

  return (
    <section className="prose max-w-none bg-white h-fit p-6 rounded-xl border border-neutral-300">
      <div className="flex items-center justify-between gap-4">
        <h1 className="text-2xl font-bold">{thread!.title}</h1>
        {session &&
          (session!.user.id === thread?.authorId ||
            (session && role === "ADMIN")) && (
            <Button
              asChild
              className="bg-blue-600 hover:bg-blue-500 transition-colors duration-150 flex items-center gap-1"
            >
              <Link href={`/thread/${thread!.id}/edit`}>
                <Pencil size={16} />
                <span>Edit</span>
              </Link>
            </Button>
          )}
      </div>
      <Separator className="mb-4" />
      <Markdown remarkPlugins={[remarkGfm]}>{thread!.content}</Markdown>
    </section>
  );
}
